# SimpleModel, mobilenet_v3_small, mobilenet_v3_large
model_name: mobilenet_v3_small

#Max epochs
epochs: 50

#Data path
train_path: ./data/1labels/train.json
val_path: ./data/1labels/val.json 

#Folder to save weight
weight_dir: ./weight/4labels/

#For load
pre_trained: ./weight/4labels/mobilenet_v3_small_lastest_w224_h224.pth

#for inference only:
inference_weight: ./weight/4labels/mobilenet_v3_small_best_acc_w224_h224.pth
image_folder: /home/phung/AnhHung/temp/rotated_test/

#Train image size
fixed_w: 224
fixed_h: 224

batch_size: 64

#For augment
background_dir: /home/phung/AnhHung/data/segment/bg/

#rotate angle list: [int(360*i/num_classes) for i in range(num_classes)]
num_classes: 4

